<?php

namespace rr\MagazineBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PubblicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PubblicationRepository extends EntityRepository
{
}
